name: GitHub Pages

# masterへの変更が加わるタイミングをトリガーとする
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    # Webブラウザー向けに静的コンテンツのビルドを行う
    name: Build static contents
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: yarn install

      - name: Build for production
        run: yarn run build

      - name: Upload result for next job
        uses: actions/upload-artifact@v1
        with:
          name: public
          path: public

  deploy:
    # ビルドした静的コンテンツを GitHub Pages にデプロイする
    name: Push to gh-pages branch and Deploy for GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download result from previous job
        uses: actions/download-artifact@v1
        with:
          name: public

      - name: Push to gh-pages branch and Deploy to GitHub Pages
        run: yarn run deploy
